In [4]:
import pandas as pd

dataset = pd.read_csv("LifetimeDogLicenses.csv", sep=",")
dataset.sample(10)

,_id,LicenseType,Breed,Color,DogName,OwnerZip,ExpYear,ValidDate
20922,19896376,Dog Lifetime Male,AM PITT BULL MIX,ORANGE/WHITE,JAGGER PUPS,15221,2099,2012-09-10T08:30:41
29260,19904714,Dog Lifetime Spayed Female,AUS SHEPHERD,BLUE,MACY WEIGEL,15044,2099,2022-06-17T14:34:42
27049,19902503,Dog Lifetime Duplicate,YORKSHIRE TERRIER,BLACK/TAN,KODY SQUILLER,15017,2099,2017-05-19T09:20:34
13305,19888759,Dog Lifetime Spayed Female,MIXED,GOLD,SADIE,15044,2099,2015-02-05T12:20:59
33921,19909375,Dog Lifetime Spayed Female,AUS SHEPHERD,TRI-COLOR,BELLE,15102,2099,2021-03-25T14:59:26
32159,19907613,Dog Lifetime Neutered Male,TAG,WHITE,MILO,15133,2099,2019-02-07T13:52:30
13153,19888607,Dog Lifetime Spayed Female,ENG SPRINGER SPANIE,WHITE/BLACK,NULA,15238,2099,2009-02-26T09:56:27
19416,19894870,Dog Lifetime Neutered Male,GOLDENDOODLE,BROWN,GIZMO,15137,2099,2017-08-08T13:26:34
40646,19916100,Dog Lifetime Neutered Male,DACHSHUND,BROWN,OTIS,15102,2099,2023-08-31T14:27:20
20745,19896199,Dog Lifetime Spayed Female,MIXED,WHITE/BLACK/BROWN,BELLA,15090,2099,2012-08-23T14:22:31

In [7]:
amountInZip= dict()
for index, row in dataset.iterrows():
    zip = row['OwnerZip']
    
    if zip in amountInZip:
        amountInZip[zip] = amountInZip[zip] + 1
    else:
        amountInZip[zip] = 1
print(amountInZip)

{15137: 535, 15129: 533, 15140: 86, 15238: 529, 15037: 986, 15235: 1431, 15215: 386, 15236: 1765, 15221: 609, 15131: 546, 15065: 804, 15135: 367, 15202: 686, 15101: 1320, 15216: 389, 15132: 692, 15239: 1363, 15147: 862, 15146: 1258, 15108: 1506, 15044: 1436, 15139: 321, 15237: 2475, 15112: 75, 15120: 783, 15142: 65, 15227: 1296, 15220: 285, 15234: 483, 15122: 1344, 15071: 365, 15143: 1234, 15223: 297, 15136: 555, 15241: 913, 15102: 1453, 15229: 833, 15020: 28, 15024: 440, 15090: 1212, 15116: 684, 16046: 123, 15088: 33, 15218: 321, 15145: 183, 15332: 144, 15233: 6, 15106: 647, 15104: 89, 15209: 529, 15057: 309, 15084: 514, 15018: 60, 15228: 576, 15133: 551, 15035: 105, 15126: 251, 15205: 516, 15025: 952, 15144: 272, 15068: 382, 15045: 245, 15017: 527, 15049: 74, 15028: 11, 15243: 514, 15014: 160, 15076: 42, 15148: 60, 15006: 10, 15046: 109, 15214: 192, 15034: 125, 15110: 101, 15201: 8, 15047: 27, 15212: 98, 15210: 81, 15030: 37, 15127: 8, 15063: 118, 15668: 4, 15219: 14, 15051: 27, 15085: 8, 15086: 25, 15056: 31, 15208: 8, 15003: 34, 15083: 7, 15225: 31, 15206: 8, 15330: 1, 15015: 72, 15005: 53, 15026: 57, 15207: 12, 15222: 4, 15226: 45, 15642: 7, 15007: 10, 15224: 3, 16066: 1, 15075: 22, 15217: 15, 15213: 2, 15203: 6, 15626: 1, 16059: 17, 15012: 4, 15064: 8, 33426: 1, 15232: 6, 47909: 1, 46845: 1, 15031: 8, 15091: 1, 15204: 1, 15082: 5, 15095: 1, 15230: 1, 15275: 1, 15089: 1, 16342: 1, 15211: 4, 15681: 1, 16229: 5, 15601: 1, 32081: 1, 15321: 1}